# Generated by Django 3.2.8 on 2021-10-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Craigslist_Clone_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
